// CREATE
export const CREATE_PLANOGRAM = "[PLANOGRAM] CREATE_PLANOGRAM";
export const CREATE_PLANOGRAM_SUCCESS = "[PLANOGRAM] CREATE_PLANOGRAM_SUCCESS";
// READ
export const GET_PLANOGRAM = "[PLANOGRAM] GET_PLANOGRAM";
export const GET_PLANOGRAM_SUCCESS = "[PLANOGRAM] GET_PLANOGRAM_SUCCESS";
// UPDATE
export const UPDATE_PLANOGRAM = "[PLANOGRAM] UPDATE_PLANOGRAM";
export const UPDATE_PLANOGRAM_SUCCESS = "[PLANOGRAM] UPDATE_PLANOGRAM_SUCCESS";
// DELETE
export const DELETE_PLANOGRAM = "[PLANOGRAM] DELETE_PLANOGRAM";
export const DELETE_PLANOGRAM_SUCCESS = "[PLANOGRAM] DELETE_PLANOGRAM_SUCCESS";

//LIST
export const GET_PLANOGRAMS = "[PLANOGRAM] GET_PLANOGRAMS";
export const GET_PLANOGRAMS_SUCCESS = "[PLANOGRAM] GET_PLANOGRAMS_SUCCESS";

//OTHERS
export const ACTION_FAILED = "[PLANOGRAM] ACTION_FAILED";
export const RESET_ALL = "[PLANOGRAM] RESET_ALL";

// MODALS
export const OPEN_MODAL_FORM = "[PLANOGRAM] OPEN_MODAL_FORM";
export const CLOSE_MODAL_FORM = "[PLANOGRAM] CLOSE_MODAL_FORM";
export const OPEN_DELETE_DIALOG = "[PLANOGRAM] OPEN_DELETE_DIALOG";
export const CLOSE_DELETE_DIALOG = "[PLANOGRAM] CLOSE_DELETE_DIALOG";
