// CREATE
export const CREATE_USER = "[USER] CREATE_USER";
export const CREATE_USER_SUCCESS = "[USER] CREATE_USER_SUCCESS";
// UPDATE
export const UPDATE_USER = "[USER] UPDATE_USER";
export const UPDATE_USER_SUCCESS = "[USER] UPDATE_USER_SUCCESS";
// DELETE
export const DELETE_USER = "[USER] DELETE_USER";
export const DELETE_USER_SUCCESS = "[USER] DELETE_USER_SUCCESS";
//LIST
export const GET_USERS = "[USER] GET_USERS";
export const GET_USERS_SUCCESS = "[USER] GET_USERS_SUCCESS";

//OTHERS
export const ACTION_FAILED = "[USER] ACTION_FAILED";
export const RESET_ALL = "[USER] RESET_ALL";
// MODALS
export const OPEN_MODAL_FORM = "[USER] OPEN_MODAL_FORM";
export const CLOSE_MODAL_FORM = "[USER] CLOSE_MODAL_FORM";
export const OPEN_DELETE_DIALOG = "[USER] OPEN_DELETE_DIALOG";
export const CLOSE_DELETE_DIALOG = "[USER] CLOSE_DELETE_DIALOG";

