// CREATE
export const CREATE_CUSTOMER = "[CUSTOMER] CREATE_CUSTOMER";
export const CREATE_CUSTOMER_SUCCESS = "[CUSTOMER] CREATE_CUSTOMER_SUCCESS";
// CREATE MASSIVE
export const CREATE_CUSTOMERS = "[CUSTOMER] CREATE_CUSTOMERS";
export const CREATE_CUSTOMERS_SUCCESS = "[CUSTOMER] CREATE_CUSTOMERS_SUCCESS";
// READ
export const GET_CUSTOMER = "[CUSTOMER] GET_CUSTOMER";
export const GET_CUSTOMER_SUCCESS = "[CUSTOMER] GET_CUSTOMER_SUCCESS";
// UPDATE
export const UPDATE_CUSTOMER = "[CUSTOMER] UPDATE_CUSTOMER";
export const UPDATE_CUSTOMER_SUCCESS = "[CUSTOMER] UPDATE_CUSTOMER_SUCCESS";
// DELETE
export const DELETE_CUSTOMERS = "[CUSTOMER] DELETE_CUSTOMERS";
export const DELETE_CUSTOMERS_SUCCESS = "[CUSTOMER] DELETE_CUSTOMERS_SUCCESS";

//LIST
export const GET_CUSTOMERS = "[CUSTOMER] GET_CUSTOMERS";
export const GET_CUSTOMERS_SUCCESS = "[CUSTOMER] GET_CUSTOMERS_SUCCESS";

//OTHERS
export const ACTION_FAILED = "[CUSTOMER] ACTION_FAILED";
export const RESET_ALL = "[CUSTOMER] RESET_ALL";

// MODALS
export const OPEN_MODAL_FORM = "[CUSTOMER] OPEN_MODAL_FORM";
export const CLOSE_MODAL_FORM = "[CUSTOMER] CLOSE_MODAL_FORM";
export const OPEN_DELETE_DIALOG = "[CUSTOMER] OPEN_DELETE_DIALOG";
export const CLOSE_DELETE_DIALOG = "[CUSTOMER] CLOSE_DELETE_DIALOG";
export const OPEN_MASSIVE_MODAL = "[CUSTOMER] OPEN_MASSIVE_MODAL";
export const CLOSE_MASSIVE_MODAL = "[CUSTOMER] CLOSE_MASSIVE_MODAL";

