// CREATE
export const CREATE_COMPANY = "[COMPANY] CREATE_COMPANY";
export const CREATE_COMPANY_SUCCESS = "[COMPANY] CREATE_COMPANY_SUCCESS";
// UPDATE
export const UPDATE_COMPANY = "[COMPANY] UPDATE_COMPANY";
export const UPDATE_COMPANY_SUCCESS = "[COMPANY] UPDATE_COMPANY_SUCCESS";
// DELETE
export const DELETE_COMPANY = "[COMPANY] DELETE_COMPANY";
export const DELETE_COMPANY_SUCCESS = "[COMPANY] DELETE_COMPANY_SUCCESS";
//LIST
export const GET_COMPANYS = "[COMPANY] GET_COMPANYS";
export const GET_COMPANYS_SUCCESS = "[COMPANY] GET_COMPANYS_SUCCESS";

//GET
export const GET_COMPANY = "[COMPANY] GET_COMPANY";
export const GET_COMPANY_SUCCESS = "[COMPANY] GET_COMPANY_SUCCESS";

//OTHERS
export const ACTION_FAILED = "[COMPANY] ACTION_FAILED";
export const RESET_ALL = "[COMPANY] RESET_ALL";

// MODALS

export const OPEN_DELETE_DIALOG = "[COMPANY] OPEN_DELETE_DIALOG";
export const CLOSE_DELETE_DIALOG = "[COMPANY] CLOSE_DELETE_DIALOG";
