// Auth Actions
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";
export const SIGNUP_USER = "SIGNUP_USER";
export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS";
export const SIGNUP_USER_FAILURE = "SIGNUP_USER_FAILURE";
export const LOGOUT_USER = "LOGOUT_USER";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAILURE = "LOGOUT_USER_FAILURE";
// Profile Actions
export const UPDATE_PROFILE = "[PROFILE] UPDATE_PROFILE";
export const UPDATE_PROFILE_SUCCESS = "[PROFILE] UPDATE_PROFILE_SUCCESS";

export const UPDATE_PROFILE_EMAIL = "[PROFILE] UPDATE_PROFILE_EMAIL";
export const UPDATE_PROFILE_EMAIL_SUCCESS =
  "[PROFILE] UPDATE_PROFILE_EMAIL_SUCCESS";

export const UPDATE_PROFILE_LANGUAGE = "[PROFILE] UPDATE_PROFILE_LANGUAGE";
export const UPDATE_PROFILE_LANGUAGE_SUCCESS =
  "[PROFILE] UPDATE_PROFILE_LANGUAGE_SUCCESS";

export const UPDATE_PROFILE_THEME = "[PROFILE] UPDATE_PROFILE_THEME";
export const UPDATE_PROFILE_THEME_SUCCESS =
  "[PROFILE] UPDATE_PROFILE_THEME_SUCCESS";

export const ACTION_FAILED = "[PROFILE] ACTION_FAILED";
