export const COLLAPSED_SIDEBAR = "COLLAPSED_SIDEBAR";
export const DARK_MODE = "DARK_MODE";
export const BOXED_LAYOUT = "BOXED_LAYOUT";
export const RTL_LAYOUT = "RTL_LAYOUT";
export const MINI_SIDEBAR = "MINI_SIDEBAR";
export const SEARCH_FORM_ENABLE = "SEARCH_FORM_ENABLE";
export const CHANGE_THEME_COLOR = "CHANGE_THEME_COLOR";
export const TOGGLE_SIDEBAR_IMAGE = "TOGGLE_SIDEBAR_IMAGE";
export const SET_SIDEBAR_IMAGE = "SET_SIDEBAR_IMAGE";
export const SET_LANGUAGE = "SET_LANGUAGE";
export const START_USER_TOUR = "START_USER_TOUR";
export const STOP_USER_TOUR = "STOP_USER_TOUR";
export const TOGGLE_DARK_SIDENAV = "TOGGLE_DARK_SIDENAV";

export const AGENCY_TOGGLE_MENU = "AGENCY_TOGGLE_MENU";
export const CHANGE_AGENCY_LAYOUT_BG = "CHANGE_AGENCY_LAYOUT_BG";
export const TOGGLE_MENU = "TOGGLE_MENU";

export const LOAD_USER_THEME = "LOAD_USER_THEME";
export const LOAD_USER_LANGUAGE = "LOAD_USER_LANGUAGE";

export const GET_MENU_ITEMS = "[SETTINGS] GET_MENU_ITEMS";
export const GET_MENU_ITEMS_SUCCESS = "[SETTINGS] GET_MENU_ITEMS_SUCCESS";
export const CLEAR_MENU_ITEMS = "[SETTINGS] CLEAR_MENU_ITEMS";
//OTHERS
export const ACTION_FAILED = "[SETTINGS] ACTION_FAILED";
export const RESET_ALL = "[SETTINGS] RESET_ALL";


export const TOGGLE_SHOW_CUSTOMERS = "[SETTINGS] TOGGLE_SHOW_CUSTOMERS";

