// CREATE
export const CREATE_PRODUCT = "[PRODUCT] CREATE_PRODUCT";
export const CREATE_PRODUCT_SUCCESS = "[PRODUCT] CREATE_PRODUCT_SUCCESS";
// CREATE MASSIVE
export const CREATE_PRODUCTS = "[PRODUCT] CREATE_PRODUCTS";
export const CREATE_PRODUCTS_SUCCESS = "[PRODUCT] CREATE_PRODUCTS_SUCCESS";
// READ
export const GET_PRODUCT = "[PRODUCT] GET_PRODUCT";
export const GET_PRODUCT_SUCCESS = "[PRODUCT] GET_PRODUCT_SUCCESS";
// UPDATE
export const UPDATE_PRODUCT = "[PRODUCT] UPDATE_PRODUCT";
export const UPDATE_PRODUCT_SUCCESS = "[PRODUCT] UPDATE_PRODUCT_SUCCESS";
// DELETE
export const DELETE_PRODUCTS = "[PRODUCT] DELETE_PRODUCTS";
export const DELETE_PRODUCTS_SUCCESS = "[PRODUCT] DELETE_PRODUCTS_SUCCESS";

//LIST
export const GET_PRODUCTS = "[PRODUCT] GET_PRODUCTS";
export const GET_PRODUCTS_SUCCESS = "[PRODUCT] GET_PRODUCTS_SUCCESS";

//OTHERS
export const ACTION_FAILED = "[PRODUCT] ACTION_FAILED";
export const RESET_ALL = "[PRODUCT] RESET_ALL";

// MODALS
export const OPEN_MODAL_FORM = "[PRODUCT] OPEN_MODAL_FORM";
export const CLOSE_MODAL_FORM = "[PRODUCT] CLOSE_MODAL_FORM";
export const OPEN_DELETE_DIALOG = "[PRODUCT] OPEN_DELETE_DIALOG";
export const CLOSE_DELETE_DIALOG = "[PRODUCT] CLOSE_DELETE_DIALOG";
export const OPEN_MASSIVE_MODAL = "[PRODUCT] OPEN_MASSIVE_MODAL";
export const CLOSE_MASSIVE_MODAL = "[PRODUCT] CLOSE_MASSIVE_MODAL";