// CREATE
export const CREATE_AGENT = "[AGENT] CREATE_AGENT";
export const CREATE_AGENT_SUCCESS = "[AGENT] CREATE_AGENT_SUCCESS";
// CREATE MASSIVE
export const CREATE_AGENTS = "[AGENT] CREATE_CUSTOMERS";
export const CREATE_AGENTS_SUCCESS = "[AGENT] CREATE_CUSTOMERS_SUCCESS";
// READ
export const GET_AGENT = "[AGENT] GET_AGENT";
export const GET_AGENT_SUCCESS = "[AGENT] GET_AGENT_SUCCESS";
// UPDATE
export const UPDATE_AGENT = "[AGENT] UPDATE_AGENT";
export const UPDATE_AGENT_SUCCESS = "[AGENT] UPDATE_AGENT_SUCCESS";
// DELETE
export const DELETE_AGENTS = "[AGENT] DELETE_AGENTS";
export const DELETE_AGENTS_SUCCESS = "[AGENT] DELETE_AGENTS_SUCCESS";

//LIST
export const GET_AGENTS = "[AGENT] GET_AGENTS";
export const GET_AGENTS_SUCCESS = "[AGENT] GET_AGENTS_SUCCESS";

//OTHERS
export const ACTION_FAILED = "[AGENT] ACTION_FAILED";
export const RESET_ALL = "[AGENT] RESET_ALL";

// MODALS
export const OPEN_MODAL_FORM = "[AGENT] OPEN_MODAL_FORM";
export const CLOSE_MODAL_FORM = "[AGENT] CLOSE_MODAL_FORM";
export const OPEN_DELETE_DIALOG = "[AGENT] OPEN_DELETE_DIALOG";
export const CLOSE_DELETE_DIALOG = "[AGENT] CLOSE_DELETE_DIALOG";
export const OPEN_MASSIVE_MODAL = "[AGENT] OPEN_MASSIVE_MODAL";
export const CLOSE_MASSIVE_MODAL = "[AGENT] CLOSE_MASSIVE_MODAL";