// CREATE
export const CREATE_TASK = "[TASK] CREATE_TASK";
export const CREATE_TASK_SUCCESS = "[TASK] CREATE_TASK_SUCCESS";
// CREATE MASSIVE
export const CREATE_TASKS = "[TASK] CREATE_TASKS";
export const CREATE_TASKS_SUCCESS = "[TASK] CREATE_TASKS_SUCCESS";
// READ
export const GET_TASK = "[TASK] GET_TASK";
export const GET_TASK_SUCCESS = "[TASK] GET_TASK_SUCCESS";
// UPDATE
export const UPDATE_TASK = "[TASK] UPDATE_TASK";
export const UPDATE_TASK_SUCCESS = "[TASK] UPDATE_TASK_SUCCESS";
// DELETE
export const DELETE_TASKS = "[TASK] DELETE_TASKS";
export const DELETE_TASKS_SUCCESS = "[TASK] DELETE_TASKS_SUCCESS";

//LIST
export const GET_TASKS = "[TASK] GET_TASKS";
export const GET_TASKS_SUCCESS = "[TASK] GET_TASKS_SUCCESS";

//OTHERS
export const ACTION_FAILED = "[TASK] ACTION_FAILED";
export const RESET_ALL = "[TASK] RESET_ALL";

// MODALS
export const OPEN_MODAL_FORM = "[TASK] OPEN_MODAL_FORM";
export const OPEN_EDIT_MODAL_FORM = "[TASK] OPEN_EDIT_MODAL_FORM";
export const CLOSE_MODAL_FORM = "[TASK] CLOSE_MODAL_FORM";
export const OPEN_DELETE_DIALOG = "[TASK] OPEN_DELETE_DIALOG";
export const CLOSE_DELETE_DIALOG = "[TASK] CLOSE_DELETE_DIALOG";
export const OPEN_MASSIVE_MODAL = "[TASK] OPEN_MASSIVE_MODAL";
export const CLOSE_MASSIVE_MODAL = "[TASK] CLOSE_MASSIVE_MODAL";